### ISSUE TITLE
Error: Cannot find module 'babel-runtime/core-js/object/entries'

### ISSUE THREAD

**Issue by pkarolyi** [trufflesuite/reselect-tree#12]
Hello!

I run into the problem in the title and after some debugging found out that the update of `reselect-tree` from 1.3.5 to 1.3.6 caused it. I don't truly know what exactly happens here, but attached the error message in full:

```shell
$ truffle test   
Using network 'development'.

Error: Cannot find module 'babel-runtime/core-js/object/entries'
Require stack:
- [project_dir]/node_modules/reselect-tree/index.js
- [project_dir]/node_modules/@truffle/debugger/dist/debugger.js
- [project_dir]/node_modules/truffle/build/cli.bundled.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> ([project_dir]/node_modules/reselect-tree/external "babel-runtime/core-js/object/entries":1:1)
    at __webpack_require__ ([project_dir]/node_modules/reselect-tree/webpack/bootstrap e958f07978aa008e523d:19:1)
    at Object.<anonymous> ([project_dir]/node_modules/reselect-tree/index.js:87:16)
    at __webpack_require__ ([project_dir]/node_modules/reselect-tree/webpack/bootstrap e958f07978aa008e523d:19:1)
    at [project_dir]/node_modules/reselect-tree/webpack/bootstrap e958f07978aa008e523d:62:1
    at [project_dir]/node_modules/reselect-tree/index.js:76:10
    at webpackUniversalModuleDefinition ([project_dir]/node_modules/reselect-tree/webpack/universalModuleDefinition:3:1)
    at Object.<anonymous> ([project_dir]/node_modules/reselect-tree/webpack/universalModuleDefinition:10:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
Truffle v5.5.12 (core: 5.5.12)
Node v16.14.2
```

The same project works with reselect-tree forced to 1.3.5 via package.json overrides.

**Comment by michaeljohnbennett** [comment]
I have seen the same. Something has happened post the esdoc removals. @haltman-at may know?

**Comment by pkarolyi** [comment]
Related: https://github.com/trufflesuite/truffle/issues/5074

**Comment by haltman-at** [comment]
Thanks!  I've put up #13 which we're hoping should fix the problem.
